services:
  tuning-fork:
    restart: always
    build:
      dockerfile: ./Dockerfile
    container_name: tuning-fork
    image: tuning-fork
    volumes:
      - /dev/shm:/dev/shm
    # environment:
    #   - MPICH_PORT_RANGE=2000:2100
    # ports:
    #   - 2000-2100:2000-2100
    #   - 2222:2222
