services:
  tuning-fork:
    restart: always
    build:
      dockerfile: ./Dockerfile
    container_name: tuning-fork
    image: tuning-fork
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 65022:65022
      - 60000-60100:60000-60100
